import type { AtlasData } from "@/features/atlas/types";

export const mockAtlasData: AtlasData = {
  stats: {
    learnedNodeCount: 46,
    connectionCount: 112,
    weeklyGrowth: 7,
  },
  categories: [
    { id: "network", label: "네트워크", recentlyExpanded: true },
    { id: "data-structure", label: "자료구조" },
    { id: "os", label: "운영체제" },
  ],
  nodes: [
    // 네트워크
    {
      id: "ip",
      categoryId: "network",
      label: "IP",
      mastery: "master",
      x: 70,
      y: 40,
      summary:
        "인터넷에서 각 기기를 식별하는 주소 체계예요. 패킷이 목적지를 찾아가는 기준이 됩니다.",
    },
    {
      id: "tcp",
      categoryId: "network",
      label: "TCP",
      mastery: "master",
      x: 230,
      y: 40,
      summary:
        "데이터를 순서대로, 빠짐없이 전달하는 연결 지향 프로토콜이에요. 신뢰성이 중요한 통신에 쓰여요.",
    },
    {
      id: "udp",
      categoryId: "network",
      label: "UDP",
      mastery: "learning",
      x: 90,
      y: 130,
      summary:
        "연결 설정 없이 빠르게 데이터를 보내는 프로토콜이에요. 순서 보장이나 재전송은 하지 않아요.",
    },
    {
      id: "http",
      categoryId: "network",
      label: "HTTP",
      mastery: "learning",
      x: 260,
      y: 110,
      summary: "웹 브라우저와 서버가 리소스를 주고받는 요청-응답 프로토콜이에요.",
    },
    {
      id: "dns",
      categoryId: "network",
      label: "DNS",
      mastery: "master",
      x: 100,
      y: 220,
      summary: "도메인 이름을 IP 주소로 변환해주는 분산 조회 시스템이에요.",
    },
    {
      id: "tls",
      categoryId: "network",
      label: "TLS",
      mastery: "unlearned",
      x: 250,
      y: 190,
      summary: "통신 구간을 암호화해 도청과 변조를 막는 보안 프로토콜이에요.",
    },
    {
      id: "streaming",
      categoryId: "network",
      label: "스트리밍",
      mastery: "unlearned",
      x: 190,
      y: 230,
      summary: "데이터를 끊지 않고 순차적으로 전송·재생하는 전송 방식이에요.",
    },
    // 자료구조
    {
      id: "array",
      categoryId: "data-structure",
      label: "배열",
      mastery: "master",
      x: 60,
      y: 40,
      summary: "같은 크기의 데이터를 연속된 메모리에 저장해 인덱스로 빠르게 접근하는 구조예요.",
    },
    {
      id: "linked-list",
      categoryId: "data-structure",
      label: "연결리스트",
      mastery: "learning",
      x: 220,
      y: 40,
      summary: "노드가 다음 노드를 가리키며 이어지는 구조예요. 삽입·삭제가 유리해요.",
    },
    {
      id: "stack",
      categoryId: "data-structure",
      label: "스택",
      mastery: "master",
      x: 60,
      y: 150,
      summary: "마지막에 넣은 데이터가 먼저 나가는 후입선출(LIFO) 구조예요.",
    },
    {
      id: "tree",
      categoryId: "data-structure",
      label: "트리",
      mastery: "unlearned",
      x: 220,
      y: 150,
      summary: "노드가 부모-자식 관계로 계층적으로 연결된 구조예요.",
    },
    // 운영체제
    {
      id: "process",
      categoryId: "os",
      label: "프로세스",
      mastery: "master",
      x: 150,
      y: 40,
      summary: "실행 중인 프로그램의 인스턴스로, 독립된 메모리 공간을 가져요.",
    },
    {
      id: "thread",
      categoryId: "os",
      label: "스레드",
      mastery: "learning",
      x: 80,
      y: 150,
      summary: "프로세스 안에서 실행되는 흐름의 단위예요. 메모리를 공유해 가벼워요.",
    },
    {
      id: "scheduling",
      categoryId: "os",
      label: "스케줄링",
      mastery: "unlearned",
      x: 220,
      y: 150,
      summary: "여러 프로세스·스레드가 CPU를 어떤 순서로 쓸지 결정하는 정책이에요.",
    },
  ],
  edges: [
    { id: "e1", fromId: "ip", toId: "tcp" },
    { id: "e2", fromId: "ip", toId: "udp" },
    { id: "e3", fromId: "udp", toId: "dns" },
    { id: "e4", fromId: "udp", toId: "streaming" },
    { id: "e5", fromId: "tcp", toId: "http" },
    { id: "e6", fromId: "tcp", toId: "tls" },
    { id: "e7", fromId: "array", toId: "linked-list" },
    { id: "e8", fromId: "array", toId: "stack" },
    { id: "e9", fromId: "stack", toId: "tree" },
    { id: "e10", fromId: "process", toId: "thread" },
    { id: "e11", fromId: "process", toId: "scheduling" },
  ],
};
